# Generated by Django 5.2.5 on 2025-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Sold', 'Sold')], default='Pending', max_length=50),
        ),
    ]
