# Generated by Django 5.2.5 on 2025-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_review_unique_together_review_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
