# Generated by Django 5.2.5 on 2025-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Sold', 'Sold'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
